import json
import numpy as np
import matplotlib.pyplot as plt
from pathlib import Path


def visualize_dataset(
    path: str | Path,
    indices: list[int] | None = None,
    max_cols: int = 5,
    figsize_per_cell: tuple[float, float] = (3.0, 3.0),
) -> None:
    """Visualize samples from a dataset generated by DatasetGeneration.generate_dataset.

    Displays a grid where each row shows one simulation sample with 3 columns:
    ground truth, observed map, and observed mask.

    Parameters
    ----------
    path : str | Path
        Path to the .npz dataset file.
    indices : list[int] | None
        Indices of samples to display. If None, all samples are shown
        (capped at max_cols).
    max_cols : int
        Maximum number of samples to display when indices is None.
    figsize_per_cell : tuple[float, float]
        Width and height of each subplot cell in inches.
    """
    path = Path(path)
    data = np.load(path, allow_pickle=False)

    ground_truths = data["ground_truth"]   # (N, H, W)
    observed_maps = data["observed_map"]   # (N, H, W)
    observed_masks = data["observed_mask"] # (N, H, W)

    n_total = ground_truths.shape[0]

    if indices is None:
        indices = list(range(min(n_total, max_cols)))

    n_samples = len(indices)
    n_rows = 3
    n_cols = n_samples

    fig, axes = plt.subplots(
        n_rows, n_cols,
        figsize=(figsize_per_cell[0] * n_cols, figsize_per_cell[1] * n_rows),
        squeeze=False,
    )

    row_labels = ["Ground Truth", "Observed Map", "Observed Mask"]
    arrays = [ground_truths, observed_maps, observed_masks]

    # Shared vmin/vmax for ground truth and observed map
    gt_vmax = ground_truths[indices].max()
    obs_vmax = observed_maps[indices].max()

    for col, idx in enumerate(indices):
        for row in range(n_rows):
            ax = axes[row, col]
            arr = arrays[row][idx]

            if row == 0:
                im = ax.imshow(arr, cmap="hot", vmin=0, vmax=10.0 or 1)
                fig.colorbar(im, ax=ax, fraction=0.046, pad=0.04)
            elif row == 1:
                im = ax.imshow(arr, cmap="hot", vmin=0, vmax=10.0 or 1)
                fig.colorbar(im, ax=ax, fraction=0.046, pad=0.04)
            else:
                ax.imshow(arr, cmap="gray", vmin=0, vmax=1)

            ax.set_xticks([])
            ax.set_yticks([])

            if col == 0:
                ax.set_ylabel(row_labels[row], fontsize=10)
            if row == 0:
                ax.set_title(f"Sample {idx}", fontsize=10)

    # Load metadata if present
    title = path.stem
    if "metadata" in data:
        try:
            meta = json.loads(bytes(data["metadata"]).decode("utf-8"))
            model_type = meta.get("observation_model_type", "?")
            steps_range = meta.get("steps_range", "?")
            title = (
                f"{meta.get('dataset_name', path.stem)}  |  "
                f"model={model_type}  |  steps={steps_range}"
            )
        except Exception:
            pass

    fig.suptitle(title, fontsize=12, y=1.01)
    plt.tight_layout()
    plt.show()


if __name__ == "__main__":
    import sys

    if len(sys.argv) < 2:
        # Try to find the most recent dataset in Datasets/
        datasets_dir = Path("Datasets")
        npz_files = sorted(datasets_dir.glob("*.npz"), key=lambda p: p.stat().st_mtime, reverse=True)
        if not npz_files:
            print("No .npz files found in Datasets/. Run DatasetGeneration.py first.")
            sys.exit(1)
        dataset_path = npz_files[0]
        print(f"Visualizing most recent dataset: {dataset_path}")
    else:
        dataset_path = Path(sys.argv[1])

    visualize_dataset(dataset_path)